name: vehicle_server Workflow

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Settings NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test